[Interviews] Fixes de ortografía 🤓🙈
laplatajs/laplatajs.github.io pull request #21
Opened 2018-06-01 22:33 UTC by juanmanuelramallo

2018-06-01 22:49 UTC, dpaez requested changes
Los cambios lucen bien, pero debemos mantener los dos espacios que agregamos en el final de algunas líneas con el fin de generar line breaks en markdown.

2018-06-01 23:41 UTC, juanmanuelramallo commented
Ahh oki muy bien!

2018-06-04 20:35 UTC, dpaez approved these changes

2018-06-04 20:35 UTC, merged

2018-06-04 20:36 UTC, dpaez commented
Gracias @juanmanuelramallo x la ayuda 👍